### ISSUE TITLE
:div.product.column.col-3.col-xs-6.p-1

### ISSUE THREAD

**Issue by JAremko** [piranha/ecomspark#1]
# :raised_eyebrow:

**Comment by piranha** [comment]
?

**Comment by JAremko** [comment]
...

**Comment by piranha** [comment]
Ну можно написать `[:div {:class "a b c d e"}]`, но мне кажется, что в целом в большом проекте всё равно оно не так будет делаться. :)

**Comment by JAremko** [comment]
@piranha  ИМХО в демке должно быть как можно меньше шума.

**Comment by piranha** [comment]
Но какой это шум, это цсс? А что, сильно сбивает с толку?

**Comment by JAremko** [comment]
Что бы ответить на этот вопрос нужна камера с :eyes:  тракером и :lab_coat:  :rabbit:  без профессиональной деформации.

**Comment by JAremko** [comment]
Понятно что в коде демки должен быть сервер, верстка (так как фишка фреймворка в том что она как есть отдается) но нужны ли кишки css селекторов  :thinking:

**Comment by JAremko** [comment]
Если провести псевдонаучный анализ, то, с точки зрения псевдо эксперта по визуальному дизайн, элементы с высокой частотой под элементов (количество саб элементов на см квадратный экрана) привлекают к себе внимания.
 Точка `.` является разделителем, с точки зрения деванного лингвиста. Соединённые точками классы организуются в слово - слово с высокой частотой под слов.  Это,  с точки зрения библиотекаря-любителя, нарушает нормальный поток чтения документа.

**Comment by piranha** [comment]
Шото ты загоняешься, диванные лингвисты не должны читать код с цсс-селекторами)

**Comment by JAremko** [comment]
> Ну можно написать `[:div {:class "a b c d e"}]`, но мне кажется, что в целом в большом проекте всё равно оно не так будет делаться. :)

@piranha  Знайти css-ера який буде не проти залізти в код і поміняти `:div.product.column.col-3.col-xs-6.p-1` на `:div.product.column.col-4.col-xs-6.p-1` напевно не так-то просто :grimacing:  А взагалі, як ви з дизайнерами і т.п працюєте? hiccup/garden індоктринація? :shipit:

**Comment by piranha** [comment]
Та на шару знайти, це ж тупо синтаксис цсс-селекторів. :) 

Гарден не юзаємо, а хікап взагалі на шару заходить, кажемо "ото так шаблони виглядають". Люди ж не тупі, воно ж дуже просто, особливо якщо ти йому паредіт поясниш.
