### ISSUE TITLE
Lack of content

### ISSUE THREAD

**Issue by JAremko** [piranha/ecomspark#5]
Nothing to watch at YT HALP
# 😱

**Comment by piranha** [comment]
a little bit too busy lately 😁

**Comment by JAremko** [comment]
![https://i.ytimg.com/vi/ZXsQAXx_ao0/maxresdefault.jpg](https://i.ytimg.com/vi/ZXsQAXx_ao0/maxresdefault.jpg)

**Comment by JAremko** [comment]
![68747470733a2f2f692e7974696d672e636f6d2f76692f5a5873514158785f616f302f6d617872657364656661756c742e6a7067 (1)](https://user-images.githubusercontent.com/1898905/124368030-98bcd900-dc11-11eb-8d47-202df69bb6e2.jpg)


# **F**
